config/routes.rb
Rails.application.routes.draw do

  root 'teams#league'
  get 'league' => 'teams#league'
  get 'eastern' => 'teams#eastern'
  get 'western' => 'teams#western'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
  scope :eastern, -> { where(conference: "Eastern")}
  scope :western, -> { where(conference: "Western")}
  

  scope :sort_by_wins, -> { order(wins: :desc) }
  scope :sort_by_losses, -> { order(losses: :desc) }


  def win_rate
    "#{(100 * wins / (wins + losses.to_f)).round(1).to_s}%"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_sorted

  def league

  end

  def eastern
    @teams = Team.eastern

  end

  def western
    @teams = Team.western
  end

  private 


  def set_sorted
    @teams  = case params[:sort]
      when "by_wins"
        Team.all.sort_by_wins
      when "by_losses"
        Team.all.sort_by_losses
      else
        Team.all
      end   
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbaStandings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <a class="navbar-brand" href="<%=root_path%>">League</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <div class="navbar-nav">
         <a class="nav-item nav-link" href="<%=eastern_path%>">Eastern</span></a>
         <a class="nav-item nav-link" href="<%=western_path%>">Western</a>
       </div>
     </div>
   </nav>
    <%= yield %>
  </body>
</html>